### ISSUE TITLE
TypeError: no implicit conversion of nil into String

### ISSUE THREAD

**Issue by andreistangacianu** [alchapone/polymer-paper-rails#8]
So - after adding all the `require`s and running `rake assets:precompile` I'm getting this error:

TypeError: no implicit conversion of nil into String
  (in /Users/andrei/.rvm/gems/ruby-2.1.1/gems/polymer-paper-rails-0.2.5/app/assets/components/core-dropdown/metadata.html)

I'm using `ruby 2.1.1p76` on rails 4.0.8.
Do you have any idea what might have gone wrong here ?

**Comment by jambyung** [comment]
I'm having exactly same issue. running rake assets:precompile gives me exactly same error.
Ruby 2.2.0 Rails 4.2
TypeError: no implicit conversion of nil into String
  (in /Users/me/.rvm/gems/ruby-2.1.5/gems/polymer-paper-rails-0.2.5/app/assets/components/core-dropdown/metadata.html)

/Users/me/.rvm/gems/ruby-2.1.5/gems/sprockets-2.12.3/lib/sprockets/context.rb:80:in `initialize'
/Users/me/.rvm/gems/ruby-2.1.5/gems/sprockets-2.12.3/lib/sprockets/context.rb:80:in `new'
/Users/me/.rvm/gems/ruby-2.1.5/gems/sprockets-2.12.3/lib/sprockets/context.rb:80:in `resolve'
/Users/me/.rvm/gems/ruby-2.1.5/gems/sprockets-2.12.3/lib/sprockets/context.rb:146:in `require_asset'
/Users/me/.rvm/gems/ruby-2.1.5/gems/polymer-rails-0.2.6/lib/polymer-rails/processors/components_processor.rb:23:in `block in require_imports'
/Users/me/.rvm/gems/ruby-2.1.5/gems/nokogiri-1.6.5/lib/nokogiri/xml/node_set.rb:237:in `block in each'
/Users/me/.rvm/gems/ruby-2.1.5/gems/nokogiri-1.6.5/lib/nokogiri/xml/node_set.rb:236:in `upto'
/Users/me/.rvm/gems/ruby-2.1.5/gems/nokogiri-1.6.5/lib/nokogiri/xml/node_set.rb:236:in `each'
/Users/me/.rvm/gems/ruby-2.1.5/gems/polymer-rails-0.2.6/lib/polymer-rails/processors/components_processor.rb:22:in `require_imports'
/Users/me/.rvm/gems/ruby-2.1.5/gems/polymer-rails-0.2.6/lib/polymer-rails/processors/components_processor.rb:15:in `process'
/Users/me/.rvm/gems/ruby-2.1.5/gems/polymer-rails-0.2.6/lib/polymer-rails/railtie.rb:18:in `block (2 levels) in <class:Railtie>'
/Users/me/.rvm/gems/ruby-2.1.5/gems/sprockets-2.12.3/lib/sprockets/processor.rb:29:in `call'
/Users/me/.rvm/gems/ruby-2.1.5/gems/sprockets-2.12.3/lib/sprockets/processor.rb:29:in `evaluate'
/Users/me/.rvm/gems/ruby-2.1.5/gems/tilt-1.4.1/lib/tilt/template.rb:103:in `render'
/Users/me/.rvm/gems/ruby-2.1.5/gems/sprockets-2.12.3/lib/sprockets/context.rb:197:in `block in evaluate'
/Users/me/.rvm/gems/ruby-2.1.5/gems/sprockets-2.12.3/lib/sprockets/context.rb:194:in `each'
/Users/me/.rvm/gems/ruby-2.1.5/gems/sprockets-2.12.3/lib/sprockets/context.rb:194:in `evaluate'
/Users/me/.rvm/gems/ruby-2.1.5/gems/sprockets-2.12.3/lib/sprockets/processed_asset.rb:12:in `initialize'
/Users/me/.rvm/gems/ruby-2.1.5/gems/sprockets-2.12.3/lib/sprockets/base.rb:374:in `new'
/Users/me/.rvm/gems/ruby-2.1.5/gems/sprockets-2.12.3/lib/sprockets/base.rb:374:in `block in build_asset'
/Users/me/.rvm/gems/ruby-2.1.5/gems/sprockets-2.12.3/lib/sprockets/base.rb:395:in `circular_call_protection'
/Users/me/.rvm/gems/ruby-2.1.5/gems/sprockets-2.12.3/lib/sprockets/base.rb:373:in `build_asset'
/Users/me/.rvm/gems/ruby-2.1.5/gems/sprockets-2.12.3/lib/sprockets/index.rb:94:in `block in build_asset'
/Users/me/.rvm/gems/ruby-2.1.5/gems/sprockets-2.12.3/lib/sprockets/caching.rb:58:in `cache_asset'
/Users/me/.rvm/gems/ruby-2.1.5/gems/sprockets-2.12.3/lib/sprockets/index.rb:93:in `build_asset'
/Users/me/.rvm/gems/ruby-2.1.5/gems/sprockets-2.12.3/lib/sprockets/base.rb:287:in `find_asset'
/Users/me/.rvm/gems/ruby-2.1.5/gems/sprockets-2.12.3/lib/sprockets/index.rb:61:in `find_asset'
/Users/me/.rvm/gems/ruby-2.1.5/gems/sprockets-2.12.3/lib/sprockets/bundled_asset.rb:16:in `initialize'
/Users/me/.rvm/gems/ruby-2.1.5/gems/sprockets-2.12.3/lib/sprockets/base.rb:377:in `new'
/Users/me/.rvm/gems/ruby-2.1.5/gems/sprockets-2.12.3/lib/sprockets/base.rb:377:in `build_asset'
/Users/me/.rvm/gems/ruby-2.1.5/gems/sprockets-2.12.3/lib/sprockets/index.rb:94:in `block in build_asset'
/Users/me/.rvm/gems/ruby-2.1.5/gems/sprockets-2.12.3/lib/sprockets/caching.rb:58:in `cache_asset'
/Users/me/.rvm/gems/ruby-2.1.5/gems/sprockets-2.12.3/lib/sprockets/index.rb:93:in `build_asset'
/Users/me/.rvm/gems/ruby-2.1.5/gems/sprockets-2.12.3/lib/sprockets/base.rb:287:in `find_asset'
/Users/me/.rvm/gems/ruby-2.1.5/gems/sprockets-2.12.3/lib/sprockets/index.rb:61:in `find_asset'
/Users/me/.rvm/gems/ruby-2.1.5/gems/sprockets-2.12.3/lib/sprockets/manifest.rb:211:in `block in find_asset'
/Users/me/.rvm/gems/ruby-2.1.5/gems/sprockets-2.12.3/lib/sprockets/manifest.rb:257:in `benchmark'
/Users/me/.rvm/gems/ruby-2.1.5/gems/sprockets-2.12.3/lib/sprockets/manifest.rb:210:in `find_asset'
/Users/me/.rvm/gems/ruby-2.1.5/gems/sprockets-2.12.3/lib/sprockets/manifest.rb:119:in `block in compile'
/Users/me/.rvm/gems/ruby-2.1.5/gems/sprockets-2.12.3/lib/sprockets/manifest.rb:118:in `each'
/Users/me/.rvm/gems/ruby-2.1.5/gems/sprockets-2.12.3/lib/sprockets/manifest.rb:118:in `compile'
/Users/me/.rvm/gems/ruby-2.1.5/gems/sprockets-rails-2.2.4/lib/sprockets/rails/task.rb:70:in `block (3 levels) in define'
/Users/me/.rvm/gems/ruby-2.1.5/gems/sprockets-2.12.3/lib/rake/sprocketstask.rb:146:in `with_logger'
/Users/me/.rvm/gems/ruby-2.1.5/gems/sprockets-rails-2.2.4/lib/sprockets/rails/task.rb:69:in `block (2 levels) in define'
/Users/me/.rvm/gems/ruby-2.1.5/bin/ruby_executable_hooks:15:in `eval'
/Users/me/.rvm/gems/ruby-2.1.5/bin/ruby_executable_hooks:15:in `<main>'
Tasks: TOP => assets:precompile

**Comment by ephraimrothschild** [comment]
Same thing here
Ruby `2.1.5` on windows
rails `4.2.0`

    DL is deprecated, please use Fiddle
    DL is deprecated, please use Fiddle
    element template: validity error : ID imports already defined
    rake aborted!
    TypeError: no implicit conversion of nil into String
      (in C:/Ruby21-x64/lib/ruby/gems/2.1.0/gems/polymer-paper-rails-0.2.5/app/assets/components/core-dropdown/metadata.html)

    Tasks: TOP => assets:precompile
    (See full trace by running task with --trace)

**Comment by jasonwill** [comment]
I've patched both core and paper to play nicely with the asset pipeline. Tested with Ruby 2.1.5/Rails 4.2.0 on Yosemite and Ubuntu 14.04. Will submit a pull request but feel free to use these if you're in a pinch:

https://github.com/jasonwill/polymer-core-rails.git
https://github.com/jasonwill/polymer-paper-rails.git

**Comment by tikitikifoofoo** [comment]
@jasonwill those forks fixed it for me. thanks!

**Comment by shawntoffel** [comment]
@jasonwill Are you still planning to submit a pull request?

**Comment by shawntoffel** [comment]
The metadata file causing the issue has been removed in version 0.5.5. See https://github.com/Polymer/core-dropdown/pull/8. I am currently working on a version bump to paper-elements 0.5.5.
